export const Gloss = {
  AA: 'addressee authority',
  ABESS: 'abessive case',
  ABIL: 'capability',
  ABL: 'ablative case',
  ABM: 'ablative-modalis case',
  ABS: 'absolutive case',
  ABSL: 'absolute',
  ABST: 'abstract; abstractive',
  ABSTR: 'abstract (of nominal)',
  ABSV: 'absentive',
  ABT: 'about',
  ABV: 'above deictic center',
  AC: 'animacy classifier',
  ACC: 'accusative case',
  ACCOM: 'accompanier',
  ACH: 'achievement',
  ACP: 'accompaniment',
  ACR: 'actor role',
  ACT: 'active voice',
  ACTL: 'actualizing',
  ACTY: 'activity',
  AD: 'near, by',
  ADAP: 'adaptive',
  ADD: 'additive case; additive focus',
  ADESS: 'adessive case',
  ADEL: 'adelative',
  ADJ: 'adjective',
  ADJZ: 'adjectivizer',
  ADM: 'admonitive mood',
  ADR: 'addressive; addressee-anchored/oriented/perspective',
  ADV: 'adverb; adverbial',
  ADVM: 'adverb marker',
  ADVS: 'adversative',
  ADVZ: 'adverbializer',
  AEQ: 'aequalis/equalis case; equational particle; equative',
  AFF: 'affirmative',
  AFFECT: 'affectionate',
  AFM: 'aforementioned',
  AFFT: 'affective case',
  AFOC: 'argument-focus marker'
};
