export const Gloss = {
  AA: 'addressee authority',
  ABESS: 'abessive case',
  ABIL: 'capability',
  ABL: 'ablative case',
  ABM: 'ablative-modalis case',
  ABS: 'absolutive case',
  ABSL: 'absolute',
  ABST: 'abstract; abstractive',
  ABSTR: 'abstract (of nominal)',
  ABSV: 'absentive',
  ABT: 'about',
  ABV: 'above deictic center',
  AC: 'animacy classifier',
  ACC: 'accusative case',
  ACCOM: 'accompanier',
  ACH: 'achievement',
  ACP: 'accompaniment',
  ACR: 'actor role',
  ACT: 'active voice',
  ACTL: 'actualizing',
  ACTY: 'activity',
  AD: 'near, by',
  ADAP: 'adaptive',
  ADD: 'additive case; additive focus',
  ADESS: 'adessive case',
  ADEL: 'adelative',
  ADJ: 'adjective',
  ADJZ: 'adjectivizer',
  ADM: 'admonitive mood',
  ADR: 'addressive; addressee-anchored/oriented/perspective',
  ADV: 'adverb; adverbial',
  ADVM: 'adverb marker',
  ADVS: 'adversative',
  ADVZ: 'adverbializer',
  AEQ: 'aequalis/equalis case; equational particle; equative',
  AFF: 'affirmative',
  AFFECT: 'affectionate',
  AFM: 'aforementioned',
  AFFT: 'affective case',
  AFOC: 'argument-focus marker',
  AFW: 'away from water',
  AGG: 'aggregate',
  AGN: 'agent nominalization/noun',
  AGR: 'agreement affix',
  AGT: 'agentive case',
  AJC: 'adjacent',
  AL: 'alienable possesion',
  ALL: 'allative case',
  ALLOC: 'allocutive',
  ALTER: 'alterphoric',
  AMBIPH: 'ambiphoric pronoun',
  AMP: 'amplifier',
  AN: 'animate gender',
  ACNR: 'action noun/nominalizer',
  ADN: 'adnominalizer',
  ANA: 'anaphoric',
  _ANA: 'action narrowly averted',
  AND: 'andative',
  ANP: 'adnominal verb',
  ANT: 'anterior tense',
  _ANT: 'antecedent',
  ANTC: 'anticipated (future); anticipating',
  ANTE: 'in front of',
  ANTEL: 'anteelative (antelative)',
  ANTESS: 'antessive case; anteessive',
  ANTIC: 'anticausative',
  _ANTIC: 'anticipatory',
  AP: 'antipassive voice',
  ANTLAT: 'antelative (ante-lative); antedirective',
  AO: 'agent-orientated verb',
  AOBL: 'attributive oblique',
  AOR: 'aorist',
  APF: 'adjective prefix',
  APL: 'applicative',
  APPOS: 'apposition; appositional mood',
  APPROB: 'approbation',
  APR: 'apprehensive mood; apprehensional',
  APRT: 'active participle; present participle',
  APRX: 'approximate',
  APUD: 'near, in the vicinity of',
  AR: 'areal',
  ARG: 'argumentative',
  ART: 'article',
  AS: 'aseverative',
  _AS: 'actor (agent-role subject)',
  ASC: 'associative case; associative plural; associative mood; compounds',
  ASP: 'aspect; aspectual',
  ASRT: 'assertive mood',
  ASSP: 'asserted past participle',
  ASSUM: 'assumptive mood; assumed evidential',
  AST: 'assistive',
  ASYM: 'asymmetric',
  AT: 'at (locative)',
  ATN: 'attention-calling',
  ATR: 'attributive; attributor',
  ATTEN: 'attenuative',
  AUD: 'auditory evidential; auditive',
  AUG: 'augmentative; augment; augmented number',
  AUX: 'auxiliary verb',
  AV: 'agent/actor voice/focus/trigger',
  AVERT: 'avertive',
  AVR: 'aversative, aversive',
  BE: "'be' verb (a conflation of EXIST and COP)",
  BEL: 'below deictic center',
  BEN: 'benefactive case',
  BG: 'background',
  BI: 'bivalent',
  BOT: 'bottom',
  BOU: 'boundary',
  BR: 'bound root',
  BT: 'boundary tone',
  BV: 'beneficiary voice/focus/trigger',
  C: 'common gender',
  _C: 'current evidence',
  __C: 'conceptualizer',
  CAR: 'caritive case',
  CARD: 'cardinal numeral',
  CAU: 'causal-final case; causal',
  CAUS: 'causitive',
  CC: 'conditional converb; clause-chain marker',
  CDM: 'core development',
  CDN: 'conjunct dubitive neutral',
  CDP: 'conjunct dubitive preterite',
  CE: 'continued event',
  CEL: 'celerative',
  CENT: 'centric case',
  CENTRIF: 'centrifugal (motion)',
  CENTRIP: 'centripetal (motion)',
  CERT: 'certainty (evidential)',
  CFOC: 'contrastive focus',
  CHEZ: "at X's place, at the home of",
  CHO: 'chômeur',
  CHR: 'cohortative',
  CIF: 'contrary information flow',
  CIRC: 'circumstantive; circumstantial voice',
  CIRCUM: '[empty tag to mark second element of a circumfix]',
  _CIRC: 'circumferential',
  CIRCUMESS: 'circumessive',
  CIS: 'cislocative',
  CIT: 'citation form ending',
  CJT: 'conjoint',
  CL: 'close link (necessary condition; temporal closeness)',
  _CL: 'nominal class (Bantu languages)',
  __CL: 'clause-level',
  CLF: 'classifier',
  CM: 'conjunction marker; noun-class marker; concatenative marker',
  CMPD: 'compound',
  CMPL: 'completive (completitive) aspect',
  CMPR: 'comparative',
  CMT: 'commitment, committal',
  CN: 'common noun',
  _CN: 'conjunct nominal',
  CNEG: 'connegative',
  CNJ: 'conjunction'
};
