export const Gloss = {
  TAMA: 'athematic tense-aspect-mood',
  AA: 'addressee authority',
  ABESS: 'abessive case',
  ABIL: 'capability',
  ABL: 'ablative case',
  ABM: 'ablative-modalis case',
  ABS: 'absolutive case',
  ABSL: 'absolute',
  ABST: 'abstract, abstractive',
  ABSTR: 'abstract (of nominal)',
  ABSV: 'absentive',
  ABT: 'about',
  ABV: 'above deictic center',
  AC: 'animacy classifier',
  ACC: 'accusative case',
  ACCOM: 'accompanier',
  ACH: 'achievement',
  ACP: 'accompaniment',
  ACR: 'actor role',
  ACT: 'active voice',
  ACTL: 'actualizing',
  ACTY: 'activity',
  AD: 'near, by',
  ADAP: 'adaptive',
  ADD: 'additive case, additive focus',
  ADESS: 'adessive case',
  ADEL: 'adelative',
  ADJ: 'adjective',
  ADJZ: 'adjectivizer',
  ADM: 'admonitive mood',
  ADR: 'addressive, addressee-anchored/oriented/perspective',
  ADV: 'adverb, adverbial',
  ADVM: 'adverb marker',
  ADVS: 'adversative',
  ADVZ: 'adverbializer',
  AEQ: 'aequalis/equalis case; equational particle; equative',
  EQA: 'active equative',
  EQS: 'stative equative',
  AFF: 'affirmative',
  AFFECT: 'affectionate',
  AFM: 'aforementioned',
  AFFT: 'affective case',
  AFOC: 'argument-focus marker',
  AFW: 'away from water',
  AGG: 'aggregate',
  AGN: 'agent nominalization/noun',
  AGR: 'agreement affix',
  AGT: 'agentive case',
  AGNZ: 'agentive nominalizer',
  AJC: 'adjacent',
  AL: 'alienable possesion',
  ALL: 'allative case',
  ALLOC: 'allocutive',
  ALTER: 'alterphoric',
  AMBIPH: 'ambiphoric pronoun',
  AMP: 'amplifier',
  AN: 'animate gender',
  ANPL: 'animate plural',
  ACNR: 'action noun/nominalizer',
  ADN: 'adnominalizer',
  ANA: 'anaphoric',
  _ANA: 'action narrowly averted',
  AND: 'andative',
  ANP: 'adnominal verb',
  ANT: 'anterior tense',
  _ANT: 'antecedent',
  ANTA: 'athematic antecedent',
  ANTT: 'thematic antecedent',
  ANTC: 'anticipated (future), anticipating',
  ANTE: 'in front of',
  ANTEL: 'anteelative (antelative)',
  ANTESS: 'antessive case, anteessive',
  ANTIC: 'anticausative',
  _ANTIC: 'anticipatory',
  AP: 'antipassive voice',
  ANTLAT: 'antelative (ante-lative), antedirective',
  AO: 'agent-orientated verb',
  AOBL: 'attributive oblique',
  AOR: 'aorist',
  APF: 'adjective prefix',
  APL: 'applicative',
  APPOS: 'apposition, appositional mood',
  APPROB: 'approbation',
  APR: 'apprehensive mood, apprehensional',
  APRT: 'active participle; present participle',
  APRX: 'approximate',
  APUD: 'near, in the vicinity of',
  AR: 'areal',
  ARG: 'argumentative',
  ART: 'article',
  AS: 'aseverative',
  _AS: 'actor (agent-role subject)',
  ASC: 'associative case; associative plural; associative mood',
  ASP: 'aspect, aspectual',
  ASRT: 'assertive mood',
  ASSP: 'asserted past participle',
  ASSUM: 'assumptive mood; assumed evidential',
  AST: 'assistive',
  ASYM: 'asymmetric',
  AT: 'at (locative)',
  ATN: 'attention-calling',
  ATR: 'attributive, attributor',
  ATTEN: 'attenuative',
  AUD: 'auditory evidential; auditive',
  AUG: 'augmentative; augment; augmented number',
  AUX: 'auxiliary verb',
  AV: 'agent/actor voice/focus/trigger',
  NAV: 'non-actor voice',
  AVERT: 'avertive',
  AVR: 'aversative, aversive',
  BE: "'be' verb (a conflation of EXIST and COP)",
  BEL: 'below deictic center',
  BEN: 'benefactive case',
  BG: 'background',
  BI: 'bivalent',
  BOT: 'bottom',
  BOU: 'boundary',
  BR: 'bound root',
  BT: 'boundary tone',
  BV: 'beneficiary voice/focus/trigger',
  C: 'common gender',
  _C: 'current evidence',
  __C: 'conceptualizer',
  ABLC: 'compass ablative',
  ALLC: 'compass allative',
  CAR: 'caritive case',
  CARD: 'cardinal numeral',
  CAU: 'causal-final case; causal',
  CAUS: 'causitive',
  CC: 'conditional converb; clause-chain marker',
  CDM: 'core development',
  CDN: 'conjunct dubitive neutral',
  CDP: 'conjunct dubitive preterite',
  CE: 'continued event',
  CEL: 'celerative',
  CENT: 'centric case',
  CENTRIF: 'centrifugal (motion)',
  CENTRIP: 'centripetal (motion)',
  CERT: 'certainty (evidential)',
  CFOC: 'contrastive focus',
  CHEZ: "at X's place, at the home of",
  CHO: 'chômeur',
  CHR: 'cohortative',
  CIF: 'contrary information flow',
  CIRC: 'circumstantive; circumstantial voice',
  CIRCUM: '[empty tag to mark 2nd element of a circumfix]',
  _CIRC: 'circumferential',
  CIRCUMESS: 'circumessive',
  CIS: 'cislocative',
  CIT: 'citation form ending',
  CJT: 'conjoint',
  CL: 'close link (necessary condition; temporal closeness)',
  _CL: 'nominal class (Bantu languages)',
  __CL: 'clause-level',
  CLF: 'classifier',
  NCL: 'noun class',
  CM: 'conjunction marker; noun-class marker; concatenative marker',
  CMPD: 'compound',
  CMPL: 'completive (completitive) aspect',
  CMPR: 'comparative',
  CMT: 'commitment, committal',
  CN: 'common noun',
  _CN: 'conjunct nominal',
  CNEG: 'connegative',
  CNJ: 'conjunction',
  CNS: 'construct state/form',
  CNSQ: 'consequential',
  CNTF: 'counterfactual conditional; contrafactuality',
  CNTR: 'contrastive; contrastive focus; contrasted topic',
  _CNTR: 'continuer',
  __CNTR: 'counter-assertive',
  CEXP: 'counterexpectation',
  COCAUS: 'concomitative-causitive',
  COH: 'coherence',
  COL: 'collective number/numeral',
  COM: 'comitative case',
  COMP: 'complementizer',
  _COMP: 'compassion',
  COMPV: 'comparative case (unequal comparison)',
  COMPUL: 'compulsional',
  CON: 'conative',
  _CON: 'concrete',
  CONC: 'concessive',
  CONCP: 'concessive particle',
  _CONC: 'concurrent',
  __CONC: 'concord marker',
  COND: 'conditional mood',
  GCOND: 'given conditional',
  GCCOND: 'given concessive conditional',
  CONF: 'confirmational, confirmative',
  CONGR: 'congruent',
  CONJ: 'conjunctive (interpropositional relation), conjunct person marking',
  CONJC: 'conjectural (evidential)',
  NCONJ: 'negative conjectural',
  CONN: 'connective',
  CONR: 'connector',
  CONS: 'consecutive; concessive',
  CONSEC: 'consecutive mood',
  CONST: 'constant, constancy',
  CONT: 'continuous aspect, continuative aspect',
  _CONT: 'on a vertical surface',
  __CONT: 'in a continuous direction',
  ___CONT: 'contentive',
  COOP: 'cooperative',
  COORD: 'coordination, coordinative',
  COP: 'copula, copulative',
  COR: 'coreference, coreferential',
  CP: 'conjunctive particle',
  CQ: 'content question',
  CRAS: 'crastinal tense',
  CRD: 'cardinal pronoun',
  CRS: 'current relevance marker, currently relevant state',
  CSM: 'change of state marker',
  CSO: 'cosubordinator',
  CT: 'circumstantial topic',
  CTEXP: 'contraexpectative',
  CTG: 'contingent mood',
  CNTG: 'contiguous',
  CTM: 'contemporative',
  CTR: 'control',
  CUS: 'customary',
  CF: 'circumstantial/theme voice/focus/trigger',
  CV: 'copula verbalizer',
  _CV: 'characteristic vowel',
  __CV: 'conveyance voice',
  CVB: 'converb',
  DAT: 'dative case',
  DC: 'deictic center',
  _DC: 'downcoast',
  DD: 'discourse definite',
  DE: 'different event, change of event',
  _DE: 'discontinued event',
  '1DE': '1st person dual exclusive pronoun',
  '2DE': '2nd person dual exclusive pronoun',
  '3DE': '3rd person dual exclusive pronoun',
  DEAG: 'deagentive',
  DEB: 'debitive/obligative mood',
  DEC: 'decausitive',
  DECL: 'declarative mood',
  DED: 'deductive evidential',
  DEF: 'definite',
  DEFIN: 'definitive',
  DEFOC: 'defocus',
  DEFR: 'deferential',
  DEI: 'deixis, deictic',
  DEL: 'delative case',
  DLM: 'delimiter, delimitative, delimiting',
  _DEL: 'deliberative mood',
  DEM: 'demonstrative',
  DEM1: 'proximate demonstrative',
  DEM2: 'present/given demonstrative',
  DEM3: 'remote demonstrative',
  DENOM: 'denominal',
  DEO: 'deontic mood',
  DEOBJ: 'deobjective',
  DEP: 'dependent, dependent clause marking',
  DEPO: 'deportmentive',
  DEPR: 'depreciatory, deprecative',
  DER: 'derivation, derivational morpheme',
  DEREL: 'derelational',
  DES: 'desiderative mood',
  DESN: 'desiderative noun',
  DEST: 'destinative aspect; destinative case',
  DET: 'determiner',
  DETR: 'detransitivizer, detransitive',
  _DETR: 'detrimental',
  DFLT: 'default',
  DH: 'downhill; seaward',
  '1DI': '1st person dual inclusive pronoun',
  '2DI': '2nd person dual inclusive pronoun',
  '3DI': '3rd person dual inclusive pronoun',
  DIF: 'direct information flow',
  DIM: 'diminutive',
  DIR: 'directive, directional',
  _DIR: 'direct case; direct voice',
  __DIR: 'directed',
  DIRA: 'athematic directed',
  DIRT: 'thematic directed',
  DIS: 'dislocative',
  DISC: 'discourse marker',
  DISJ: 'disjunction, disjunctive, disjunct person marking',
  DISSAT: 'dissatisfaction',
  DIST: 'distal, distant',
  DISTR: 'distributive case; distributive plural; distributive aspect',
  DITR: 'ditransitive',
  DIV: 'diversative',
  DN: 'deverbal noun',
  DNZ: 'denizen',
  DM: 'demonstrative marker; directive marker',
  DO: 'direct object, direct objective',
  DOM: 'differential object marking; direct-object marker',
  DON: 'donative',
  DOX: 'doxastic',
  DP: 'distant past',
  _DP: 'discourse particle',
  __DP: 'destinative participle',
  DPAST: 'direct past (evidentiality)',
  DPC: 'distant past continuative',
  DPP: 'distant past completive',
  DR: 'downriver',
  _DR: 'different reference',
  DS: 'different-subject/actor/agent (change of subject) marker',
  DSC: 'discontinuative aspect',
  DT: 'different taxis',
  DTR: 'detrimentary',
  DU: 'dual number',
  DUB: 'dubitative mood, dubiative',
  DUMMY: 'dummy affix',
  DUPLIC: 'duplicative',
  DUR: 'durative aspect (continuous aspect)',
  DV: 'direction voice/focus/trigger',
  DWN: 'downward',
  DY: 'dyadic',
  DYN: 'dynamic aspect / eventive',
  EA: 'epistemic authority',
  EC: 'euphonic consonant',
  EFF: 'effector',
  EFOC: 'extra-focal',
  EGO: 'egophoric',
  NEGO: 'non-egophoric',
  EGR: 'egressive',
  ELA: 'elative case',
  ELPA: 'existential + locative + possessive + attributive',
  EM: 'extension marker; evaluative marker',
  EMO: 'emotive',
  EMP: 'emphatic; emphasizer, emphatic marker',
  END: 'clause-final particle',
  ENDO: 'endopathic',
  ENC: 'enunciative particle',
  EP: 'epenthetic morpheme, epenthetical',
  EPI: 'epistemic mood/modality',
  EPIT: 'epithet',
  EQU: 'equative',
  ERG: 'ergative case',
  ES: 'echo subject',
  ESS: 'essive case',
  EV: 'evidential',
  _EV: 'euphonic vowel',
  __EV: 'experiencer voice',
  EVIT: 'evitative case',
  EVT: 'eventual',
  EXAL: 'exaltive/deferential',
  EXC: 'excessive',
  EX: 'exclusive person',
  '1EX': '1st person exclusive pronoun',
  EXCLAM: 'exclamative, exclamatory',
  EXEC: 'executive (auxiliary)',
  EXESS: 'exessive case',
  EXFOC: 'extrafocal',
  EXH: 'exhortative, adhortative',
  EXIST: 'existential',
  EXO: 'exocentric case',
  EXPER: 'experiencer, experiencer case',
  EXP: 'experiential/eyewitness/direct evidential',
  EXPECT: 'expectational',
  EXPL: 'expletive',
  EXPR: 'expressive',
  EXT: 'extended aspect/demonstrative, extendible; extension (sound stretch)',
  _EXT: 'extent',
  __EXT: 'external evidential',
  EXTRV: 'extraversive',
  EXTT: 'extended topic',
  EZF: 'ezāfe, izafet',
  F: 'feminine gender',
  FSG: 'feminine singular',
  FPL: 'feminine plural',
  FEM: 'female speaker',
  FA: 'future actor',
  FAC: 'factive evidential/mood, factual; factitive',
  FAM: 'familiar register; familiar pronomial',
  FC: 'future conjunct',
  NFC: 'non-future conjunct',
  FCL: 'facilitive',
  FD: 'future disjunct',
  FH: 'firsthand',
  NFH: 'non-firsthand',
  FI: 'feminine indefinite',
  FILL: 'morphological filler, sentence filler (expletive)',
  FIN: 'finite verb',
  NFIN: 'non-finite verb',
  _FIN: 'finalis',
  FMR: 'former, deceased',
  FN: 'first/given name',
  FNL: 'phrase-final suffix',
  FOC: 'focus',
  AGFOC: 'agent/actor focus',
  PFOC: 'patient focus',
  LFOC: 'location focus',
  BFOC: 'beneficiary focus',
  ACFOC: 'accompanier focus',
  IFOC: 'instrument focus',
  _CFOC: 'conveyance focus',
  FOR: 'formal register; formal mood; formal case',
  FPRT: 'future participle',
  FPST: 'far past',
  FRACT: 'fraction, fractional (numeral)',
  FREQ: 'frequentive aspect',
  FRT: 'front',
  FRUS: 'frustrative',
  FS: 'false start',
  FTV: 'factative tense',
  FUNC: 'functional',
  _FUNC: 'functive case',
  FUT: 'future tense',
  FOBJ: 'future objective',
  ITF: 'intentional future',
  FV: 'final/terminal vowel',
  G1: 'gender / noun class 1',
  G2: 'gender / noun class 2',
  G3: 'gender / noun class 3',
  G4: 'gender / noun class 4',
  G5: 'gender / noun class 5',
  G6: 'gender / noun class 6',
  G7: 'gender / noun class 7',
  G8: 'gender / noun class 8',
  G9: 'gender / noun class 9',
  G10: 'gender / noun class 10',
  G11: 'gender / noun class 11',
  G12: 'gender / noun class 12',
  G13: 'gender / noun class 13',
  G14: 'gender / noun class 14',
  G15: 'gender / noun class 15',
  G16: 'gender / noun class 16',
  G17: 'gender / noun class 17',
  G18: 'gender / noun class 18',
  G19: 'gender / noun class 19',
  G20: 'gender / noun class 20',
  GEM: 'generalized evaluative marker',
  GEN: 'genitive case, genitive form of pronoun',
  GENZ: 'generalized',
  GER: 'gerund, gerundive',
  GIV: 'given',
  GKN: 'general knowledge (evidential)',
  GM: 'gender marker',
  GNF: 'general non-finite',
  GNO: 'gnomic aspect',
  GNR: 'generic, general',
  GNT: 'general tense',
  GPST: 'general past',
  GRP: 'group numeral',
  GTOP: 'given topic',
  GV: 'goal voice/focus/trigger',
  ___H: 'head',
  _H: 'hearer/reader',
  __H: 'high variety/code in a diglossic situation',
  H: 'human/anthropic gender',
  HSG: 'human singular',
  HPL: 'human plural',
  ALLH: 'human allative',
  ____H: 'higher animacy; higher object',
  HAB: 'habitual aspect',
  HBL: 'habilitive',
  HCR: 'hypocoristic',
  HES: 'hesitation, hesitation particle',
  HEST: 'hesternal tense',
  HIST: 'historic/historical',
  HNDR: 'number of hundreds',
  HOD: 'hodiernal tense',
  HON: 'honorific',
  HOR: 'horizon of interest',
  _HOR: 'horizontal',
  HORT: 'hortative',
  HRS: 'hearsay/reported evidential',
  HUM: 'humiliative, humble',
  HYP: 'hypothetical mood',
  I: 'inflected',
  IA: 'involuntary agent',
  _IA: 'indirect agent/agentive',
  __IA: 'instrumental advancement',
  IAM: 'iamitive',
  IC: 'involuntary causative',
  _IC: 'indirective copula',
  ICOM: 'involuntary comitative',
  ICVB: 'imperfective converb',
};
