export const DimenRes = {
  input: {
    label: '1em',
    input: '1em',
    button: '1em',
    description: '0.8em',
    spaceBetween: '1em',
  },
};
export const StringRes = {
  goback: 'Go Back',
  continue: 'Continue',
  glossingabbreviations: 'Glossing Abbreviations',
  done: 'Done',
  partOfSpeech: {
    noun: 'Noun',
    verb: 'Verb',
    adjective: 'Adjective',
    adverb: 'Adverb',
    pronoun: 'Pronoun',
    'proper noun': 'Proper Noun',
    particle: 'Particle',
    adposition: 'Adposition',
    conjunction: 'Conjunction',
    interjection: 'Interjection',
    abbr: {
      noun: 'N',
      verb: 'V',
      adjective: 'Adj',
      adverb: 'Adv',
      pronoun: 'Pron',
      'proper noun': 'PropN',
      particle: 'Ptcl',
      adposition: 'Adp',
      conjunction: 'Conj',
      interjection: 'Interj',
    },
    plural: {
      nouns: 'Nouns',
      verbs: 'Verbs',
      adjectives: 'Adjectives',
      adverbs: 'Adverbs',
      pronouns: 'Pronouns',
      'proper nouns': 'Proper Nouns',
      particles: 'Particles',
      adpositions: 'Adpositions',
      conjunctions: 'Conjunctions',
    },
  },
  untitled: 'Untitled',
  confirmation: 'Confirmation',
  deletearticle:
    `Are you sure you want to delete $1 and its contents? This ` +
    `cannot be undone.`,
  name: 'Name:',
  imageurl: 'Image URL',
  managephonemes:
    'Manage phonemes, allophones, etc. and their romanizations. Your ' +
    'orthography can be managed in the next section.',
  phonemesromanization: 'Phonemes & Romanization',
  ipa: 'IPA',
  type: 'Type',
  diacritics: 'Diacritics',
  allophoneof: 'Allophone of',
  romanization: 'Romanization',
  copyipa: 'Copy IPA',
  romanizationToIpa:
    'Are you sure you want to set the romanizations of all ' +
    'phonemes to their IPA values? This cannot be undone.',
  actions: 'Actions',
  diacritic: {
    consonant: {
      voiceless: 'Voiceless',
      voiced: 'Voiced',
      aspirated: 'Aspirated',
      syllabic: 'Syllabic',
      breathy: 'Breathy',
      creaky: 'Creaky',
      linguolabial: 'Linguolabial',
      labialized: 'Labialized',
      palatalized: 'Palatalized',
      velarized: 'Velarized',
      pharyngealized: 'Pharyngealized',
      'velarized/pharyngealized': 'Velarized or Pharyngealized (~)',
      raised: 'Raised',
      lowered: 'Lowered',
      dental: 'Dental',
      apical: 'Apical',
      laminal: 'Laminal',
      'nasal release': 'Nasal Release',
      'dental release': 'Dental Release',
      'no audible release': 'No Audible Release',
    },
    vowel: {
      'more rounded': 'More Rounded',
      'less rounded': 'Less Rounded',
      advanced: 'Advanced',
      retracted: 'Retracted',
      centralized: 'Centralized',
      'mid-centralized': 'Mid-Centralized',
      raised: 'Raised',
      lowered: 'Lowered',
      '+ATR': 'Advanced Tongue Root (+ATR)',
      '-ATR': 'Retracted Tongue Root (-ATR)',
      nonsyllabic: 'Nonsyllabic',
      rhoticized: 'Rhoticized',
      creaky: 'Creaky',
      breathy: 'Breathy',
      nasalized: 'Nasalized',
      long: 'Long',
      'half-long': 'Half-Long',
      'extra-short': 'Extra-Short',
    },
  },
  phoneticinventory: 'Phonetic Inventory',
  selectsounds:
    "Select sounds to add to $1's inventory. Use the next section to add " +
    'diacritics and set romanizations.',
  consonants: 'Consonants',
  vowels: 'Vowels',
  placeofarticulation: {
    bilabial: 'Bilabial',
    labiodental: 'Labiodental',
    dental: 'Dental',
    alveolar: 'Alveolar',
    postalveolar: 'Postalveolar',
    retroflex: 'Retroflex',
    alveolopalatal: 'Alveolopalatal',
    palatal: 'Palatal',
    labiovelar: 'Labiovelar',
    velar: 'Velar',
    uvular: 'Uvular',
    pharyngeal: 'Pharyngeal',
    epiglottal: 'Epiglottal',
    glottal: 'Glottal',
    other: 'Other',
  },
  mannerofarticulation: {
    plosive: 'Plosive',
    nasal: 'Nasal',
    trill: 'Trill',
    taporflap: 'Tap or Flap',
    lateralflap: 'Lateral Flap',
    fricative: 'Fricative',
    lateralfricative: 'Lateral Fricative',
    approximant: 'Approximant',
    lateralapproximant: 'Lateral Approximant',
    click: 'Click',
    implosive: 'Implosive',
  },
  backness: {
    front: 'Front',
    central: 'Central',
    back: 'Back',
  },
  height: {
    close: 'Close',
    closemid: 'Close-mid',
    openmid: 'Open-mid',
    open: 'Open',
  },
  orthography: 'Orthography',
  phonotactics: 'Phonotactics',
  sameasnoun: 'Use the same declensions as nouns',
  losedeclensions:
    'Are you sure? You will lose your currently saved declensions.',
  yes: 'Yes',
  cancel: 'Cancel',
  addtable: 'Add Table',
  adddeclension: 'Add Declension',
  nounclasses: 'Noun Classes:',
  delete: '---DELETE---',
  addaffix: 'Add Affix'
};
