export const DimenRes = {
  input: {
    label: '1em',
    input: '1em',
    button: '1em',
    description: '0.8em',
    spaceBetween: '1em',
  },
};
export const StringRes = {
  goback: 'Go Back',
  continue: 'Continue',
  glossingabbreviations: 'Glossing Abbreviations',
  done: 'Done',
  partofspeech: {
    _: {
      a: 'Part of Speech',
      b: 'Part of Speech:',
    },
    noun: 'Noun',
    verb: 'Verb',
    adjective: 'Adjective',
    adverb: 'Adverb',
    pronoun: 'Pronoun',
    'proper noun': 'Proper Noun',
    particle: 'Particle',
    adposition: 'Adposition',
    conjunction: 'Conjunction',
    interjection: 'Interjection',
    abbr: {
      noun: 'N',
      verb: 'V',
      adjective: 'Adj',
      adverb: 'Adv',
      pronoun: 'Pron',
      'proper noun': 'PropN',
      particle: 'Ptcl',
      adposition: 'Adp',
      conjunction: 'Conj',
      interjection: 'Interj',
    },
    plural: {
      nouns: 'Nouns',
      verbs: 'Verbs',
      adjectives: 'Adjectives',
      adverbs: 'Adverbs',
      pronouns: 'Pronouns',
      'proper nouns': 'Proper Nouns',
      particles: 'Particles',
      adpositions: 'Adpositions',
      conjunctions: 'Conjunctions',
    },
  },
  untitled: 'Untitled',
  confirmation: 'Confirmation',
  deletearticle:
    `Are you sure you want to delete $1 and its contents? This ` +
    `cannot be undone.`,
  name: {
    a: 'Name',
    b: 'Name:',
  },
  imageurl: 'Image URL',
  managephonemes:
    'Manage phonemes, allophones, etc. and their romanizations. Your ' +
    'orthography can be managed in the next section.',
  phonemesromanization: 'Phonemes & Romanization',
  ipa: {
    a: 'IPA',
    b: 'IPA:',
  },
  type: 'Type',
  diacritics: 'Diacritics',
  allophoneof: 'Allophone of',
  romanization: {
    a: 'Romanization',
    b: 'Romanization:',
  },
  copyipa: 'Copy IPA',
  romanizationToIpa:
    'Are you sure you want to set the romanizations of all ' +
    'phonemes to their IPA values? This cannot be undone.',
  actions: 'Actions',
  diacritic: {
    consonant: {
      voiceless: 'Voiceless',
      voiced: 'Voiced',
      aspirated: 'Aspirated',
      syllabic: 'Syllabic',
      breathy: 'Breathy',
      creaky: 'Creaky',
      linguolabial: 'Linguolabial',
      labialized: 'Labialized',
      palatalized: 'Palatalized',
      velarized: 'Velarized',
      pharyngealized: 'Pharyngealized',
      'velarized/pharyngealized': 'Velarized or Pharyngealized (~)',
      raised: 'Raised',
      lowered: 'Lowered',
      dental: 'Dental',
      apical: 'Apical',
      laminal: 'Laminal',
      'nasal release': 'Nasal Release',
      'dental release': 'Dental Release',
      'no audible release': 'No Audible Release',
    },
    vowel: {
      'more rounded': 'More Rounded',
      'less rounded': 'Less Rounded',
      advanced: 'Advanced',
      retracted: 'Retracted',
      centralized: 'Centralized',
      'mid-centralized': 'Mid-Centralized',
      raised: 'Raised',
      lowered: 'Lowered',
      '+ATR': 'Advanced Tongue Root (+ATR)',
      '-ATR': 'Retracted Tongue Root (-ATR)',
      nonsyllabic: 'Nonsyllabic',
      rhoticized: 'Rhoticized',
      creaky: 'Creaky',
      breathy: 'Breathy',
      nasalized: 'Nasalized',
      long: 'Long',
      'half-long': 'Half-Long',
      'extra-short': 'Extra-Short',
    },
  },
  phoneticinventory: 'Phonetic Inventory',
  selectsounds:
    "Select sounds to add to $1's inventory. Use the next section to add " +
    'diacritics and set romanizations.',
  consonants: 'Consonants',
  vowels: 'Vowels',
  placeofarticulation: {
    bilabial: 'Bilabial',
    labiodental: 'Labiodental',
    dental: 'Dental',
    alveolar: 'Alveolar',
    postalveolar: 'Postalveolar',
    retroflex: 'Retroflex',
    alveolopalatal: 'Alveolopalatal',
    palatal: 'Palatal',
    labiovelar: 'Labiovelar',
    velar: 'Velar',
    uvular: 'Uvular',
    pharyngeal: 'Pharyngeal',
    epiglottal: 'Epiglottal',
    glottal: 'Glottal',
    other: 'Other',
  },
  mannerofarticulation: {
    plosive: 'Plosive',
    nasal: 'Nasal',
    trill: 'Trill',
    taporflap: 'Tap or Flap',
    lateralflap: 'Lateral Flap',
    fricative: 'Fricative',
    lateralfricative: 'Lateral Fricative',
    approximant: 'Approximant',
    lateralapproximant: 'Lateral Approximant',
    click: 'Click',
    implosive: 'Implosive',
  },
  backness: {
    front: 'Front',
    central: 'Central',
    back: 'Back',
  },
  height: {
    close: 'Close',
    closemid: 'Close-mid',
    mid: 'Mid',
    openmid: 'Open-mid',
    open: 'Open',
  },
  orthography: 'Orthography',
  phonotactics: 'Phonotactics',
  sameasnoun: 'Use the same declensions as nouns',
  losedeclensions:
    'Are you sure? You will lose your currently saved declensions.',
  yes: 'Yes',
  cancel: 'Cancel',
  addtable: 'Add Table',
  adddeclension: 'Add Declension',
  wordclasses: 'Applicable Word Classes:',
  delete: '---DELETE---',
  addaffix: 'Add Affix',
  addgloss: 'Add Gloss',
  rootword: 'Root Word',
  manageclasses: 'Manage Classes',
  deleteword: 'Are you sure you want to delete $1 [$2]? This cannot be undone.',
  wordtitle: '$1 | $2 [$3]',
  newclass: 'New Class',
  gloss: 'Gloss',
  overrideautogeneration: 'Override autogeneration',
  class: 'Class:',
  definitions: 'Definitions:',
  newdefinition: 'New Definition',
  deletedefinition:
    'Are you sure you want to delete the definition "$1"? This ' +
    'cannot be undone.',
  start: 'Start',
  phonology: 'Phonology',
  articles: 'Articles',
  inflections: 'Inflections',
  lexicon: 'Lexicon',
  settings: 'Settings',
  close: 'Close',
  general: 'General',
  conlangname: {
    a: 'Conlang Name',
    d: 'Conlang name:',
  },
  nochangefilename: 'This will not change the file name.',
  autosave: 'Autosave',
  disabled: 'Disabled',
  every1min: 'Every 1 minute',
  every5min: 'Every 5 minutes',
  every10min: 'Every 10 minutes',
  custom: 'Custom:',
  timebtwnsaves: 'Time in minutes between saves',
  charinsertwidget: 'Character Inserter Widget',
  enabled: 'Enabled',
  no: 'No',
  characters: 'Characters',
  enterchars: 'Enter characters or character groups separated by commas.',
  save: 'Save',
  welcometomorpheme: 'Welcome to Morpheme!',
  openexistingconlang: 'Open Existing Conlang',
  choosefile: 'Choose File',
  createnewconlang: 'Create New Conlang',
  jsonfiles: 'JSON Files',
  submit: 'Submit',
  export: 'Export',
  exporttopdf: 'Export to PDF',
  papersize: 'Paper Size:',
  letter: 'Letter',
  a4: 'A4',
  sectionstoinclude: 'Sections to Include',
  othersettings: 'Other Settings',
  pagenumbers: 'Page Numbers',
  pagenumsincludetitle: 'Page #s Include Title Page',
  pagenumsincludetoc: 'Page #s Include Table of Contents',
  finish: 'Finish',
  titlepage: 'Title Page',
  tableofcontents: 'Table of Contents',
  createdwithmorpheme: 'Created with Morpheme',
  conlangtitle: 'Conlang Title',
  conlangauthor: 'Conlang Author',
  url: 'https://liujip0.github.io/morpheme/',
  morpheme: 'Morpheme',
  currentlyediting: 'Currently Editing:',
  import: 'Import',
  lexiconsearch: 'Lexicon Search',
  definitioncount: 'Def. Ct.',
  nowordsmatchyoursearch: 'No words match your search',
  starttypingtosearch: 'Start typing to search',
  conlangxsampa: 'Conlang X-SAMPA',
  nofilesystemapi: 'File System Access API not supported',
  unclassed: '(unclassed)',
  newversionavailable:
    'New version available. Reload? You may lose unsaved work.',
  finishedcaching: 'Morpheme has finished caching and will now work offline.',
  addconjugation: 'Add Conjugation',
};
